name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.next_version.outputs.version }}
      commit: ${{ steps.commit.outputs.short }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current version
        id: current_version
        run: |
          echo "version=v${GITHUB_REF#refs/tags/*/}"
          echo "version=v${GITHUB_REF#refs/tags/*/}" >> $GITHUB_OUTPUT

      - name: Get next version
        id: next_version
        run: |
          echo "version=v$(node -p "require('./experiment/package.json').version")"
          echo "version=v$(node -p "require('./experiment/package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        if: '${{ steps.current_version.outputs.version != steps.next_version.outputs.version }}'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.next_version.outputs.version }}
          name: Release ${{ steps.next_version.outputs.version }}

      - name: Commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3

  build: 
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build release
        run: cd ./experiment && yarn install && yarn build
        env:
          VITE_APP_URL: "https://wasm.choffmann.io"
          VITE_AUTHOR: "Cedrik Hoffmann"
          VITE_APP_VERSION: ${{ needs.create_release.outputs.version }}
          VITE_CURRENT_BRANCH: main
          VITE_LAST_COMMIT: ${{ needs.create_release.outputs.version }}

