name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current version
        id: current_version
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Get next version
        id: next_version
        run: echo "version=$(node -p "require('./experiment/package.json').version")" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        if: steps.current_version.outputs.version != steps.next_version.outputs.version 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.next_version.outputs.version }}
          release_name: Release v${{ steps.next_version.outputs.version }}
          draft: false
          prerelease: false
