name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build release
        run: cd ./experiment && yarn install && yarn build

  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get next version
        id: next_version
        run: |
          echo "version=v$(node -p "require('./experiment/package.json').version")"
          echo "version=v$(node -p "require('./experiment/package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        continue-on-error: true
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.next_version.outputs.version }}
          name: Release ${{ steps.next_version.outputs.version }}

      - name: Commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3


